name: Daily Auto Upload
on:
  schedule:
    - cron: "30 4 * * *" # Runs at 4:30 AM UTC
  workflow_dispatch: # Allows manual testing

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your code
        uses: actions/checkout@v4 # Updated from v3 to v4

      - name: Move one file
        run: python drip_feed.py

      - name: Commit and Push to GitHub
        run: |
          git config --global user.name "sushant-me"
          git config --global user.email "sushant.poudel2028@gmail.com"
          git add .
          git commit -m "Auto-update: Daily Python Practice" || exit 0
          git push
